"""empty message

Revision ID: b9ec9985f0a3
Revises: bb55c647f626
Create Date: 2020-01-20 16:33:50.318393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ec9985f0a3'
down_revision = 'bb55c647f626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indentity', sa.String(length=500), nullable=True),
    sa.Column('city_name', sa.String(length=200), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=30), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('pres', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('rh', sa.Integer(), nullable=True),
    sa.Column('wind_spd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_indentity'), 'weather', ['indentity'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_indentity'), table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
