"""empty message

Revision ID: bb55c647f626
Revises: 957baf664637
Create Date: 2020-01-19 00:23:44.743644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb55c647f626'
down_revision = '957baf664637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('indentity', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_weather_indentity'), 'weather', ['indentity'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_indentity'), table_name='weather')
    op.drop_column('weather', 'indentity')
    # ### end Alembic commands ###
